# steam_api_bridge Winelib spec file

# Core API calls
@ cdecl SteamAPI_InitSafe_()
@ cdecl SteamAPI_Shutdown_()
@ cdecl SteamAPI_RegisterCallback_(ptr ptr ptr long long)
@ cdecl SteamAPI_UnregisterCallback_(ptr)
@ cdecl SteamAPI_RunCallbacks_()

# SteamClient API Calls
@ cdecl SteamClient_()
@ cdecl SteamClient_SetWarningMessageHook(ptr)

# SteamUser API calls
@ cdecl SteamUser_(str)
@ cdecl SteamUser_GetHSteamUser(ptr)
@ cdecl SteamUser_GetSteamID(ptr ptr)
@ cdecl SteamUser_BLoggedOn(ptr)
#@ cdecl steam_bridge_SteamUser_InitiateGameConnection(ptr ptr long int64 long word long)
# TODO: Second to last parameter is an unsigned short (16-bits) -
#       Winelib documenation suggests this is still a 'long'
@ cdecl SteamUser_InitiateGameConnection(ptr ptr long int64 long long long)
#@ cdecl steam_bridge_SteamUser_TerminateGameConnection(ptr long word)
@ cdecl SteamUser_TerminateGameConnection(ptr long long)
@ cdecl SteamUser_TrackAppUsageEvent(ptr int64 long str)
@ cdecl SteamUser_GetUserDataFolder(ptr ptr long)
@ cdecl SteamUser_StartVoiceRecording(ptr)
@ cdecl SteamUser_StopVoiceRecording(ptr)
@ cdecl SteamUser_GetAvailableVoice(ptr ptr ptr long)
@ cdecl SteamUser_GetVoice(ptr long ptr long ptr long ptr long ptr long)
@ cdecl SteamUser_DecompressVoice(ptr ptr long ptr long ptr long)
@ cdecl SteamUser_GetVoiceOptimalSampleRate(ptr)
@ cdecl SteamUser_GetAuthSessionTicket(ptr ptr long ptr)
@ cdecl SteamUser_BeginAuthSession(ptr ptr long int64)
@ cdecl SteamUser_EndAuthSession(ptr int64)
@ cdecl SteamUser_CancelAuthTicket(ptr long)
@ cdecl SteamUser_UserHasLicenseForApp(ptr int64 long)
@ cdecl SteamUser_BIsBehindNAT(ptr)
@ cdecl SteamUser_AdvertiseGame(ptr int64 long long)
@ cdecl -ret64 SteamUser_RequestEncryptedAppTicket(ptr ptr long)
@ cdecl SteamUser_GetEncryptedAppTicket(ptr ptr long ptr)

# SteamFriends API Calls
@ cdecl SteamFriends_()
@ cdecl SteamFriends_GetPersonaName(ptr)
@ cdecl -ret64 SteamFriends_SetPersonaName(ptr str)
@ cdecl SteamFriends_GetPersonaState(ptr)
@ cdecl SteamFriends_GetFriendCount(ptr long)
@ cdecl SteamFriends_GetFriendByIndex(ptr long long ptr)
@ cdecl SteamFriends_GetFriendRelationship(ptr int64)
@ cdecl SteamFriends_GetFriendPersonaState(ptr int64)
@ cdecl SteamFriends_GetFriendPersonaName(ptr int64)
@ cdecl SteamFriends_GetFriendGamePlayed(ptr int64 ptr)
@ cdecl SteamFriends_GetFriendPersonaNameHistory(ptr int64 long)
@ cdecl SteamFriends_HasFriend(ptr int64 long)
@ cdecl SteamFriends_GetClanCount(ptr)
@ cdecl SteamFriends_GetClanByIndex(ptr long ptr)
@ cdecl SteamFriends_GetClanName(ptr int64)
@ cdecl SteamFriends_GetClanTag(ptr int64)
@ cdecl SteamFriends_GetClanActivityCounts(ptr int64 ptr ptr ptr)
@ cdecl -ret64 SteamFriends_DownloadClanActivityCounts(ptr ptr long)
@ cdecl SteamFriends_GetFriendCountFromSource(ptr int64)
@ cdecl SteamFriends_GetFriendFromSourceByIndex(ptr int64 long ptr)
@ cdecl SteamFriends_IsUserInSource(ptr int64 int64)
@ cdecl SteamFriends_SetInGameVoiceSpeaking(ptr int64 long)
@ cdecl SteamFriends_ActivateGameOverlay(ptr str)
@ cdecl SteamFriends_ActivateGameOverlayToUser(ptr str int64)
@ cdecl SteamFriends_ActivateGameOverlayToWebPage(ptr str)
@ cdecl SteamFriends_ActivateGameOverlayToStore(ptr long long)
@ cdecl SteamFriends_SetPlayedWith(ptr int64)
@ cdecl SteamFriends_ActivateGameOverlayInviteDialog(ptr int64)
@ cdecl SteamFriends_GetSmallFriendAvatar(ptr int64)
@ cdecl SteamFriends_GetMediumFriendAvatar(ptr int64)
@ cdecl SteamFriends_GetLargeFriendAvatar(ptr int64)
@ cdecl SteamFriends_RequestUserInformation(ptr int64 long)
@ cdecl -ret64 SteamFriends_RequestClanOfficerList(ptr int64)
@ cdecl SteamFriends_GetClanOwner(ptr int64 ptr)
@ cdecl SteamFriends_GetClanOfficerCount(ptr int64)
@ cdecl SteamFriends_GetClanOfficerByIndex(ptr int64 long ptr)
@ cdecl SteamFriends_GetUserRestrictions(ptr)
@ cdecl SteamFriends_SetRichPresence(ptr str str)
@ cdecl SteamFriends_ClearRichPresence(ptr)
@ cdecl SteamFriends_GetFriendRichPresence(ptr int64 str)
@ cdecl SteamFriends_GetFriendRichPresenceKeyCount(ptr int64)
@ cdecl SteamFriends_GetFriendRichPresenceKeyByIndex(ptr int64 long)
@ cdecl SteamFriends_RequestFriendRichPresence(ptr int64)
@ cdecl SteamFriends_InviteUserToGame(ptr int64 str)
@ cdecl SteamFriends_GetCoplayFriendCount(ptr)
@ cdecl SteamFriends_GetCoplayFriend(ptr long ptr)
@ cdecl SteamFriends_GetFriendCoplayTime(ptr int64)
@ cdecl SteamFriends_GetFriendCoplayGame(ptr int64)
@ cdecl -ret64 SteamFriends_JoinClanChatRoom(ptr int64)
@ cdecl SteamFriends_LeaveClanChatRoom(ptr int64)
@ cdecl SteamFriends_GetClanChatMemberCount(ptr int64)
@ cdecl SteamFriends_GetChatMemberByIndex(ptr int64 long ptr)
@ cdecl SteamFriends_SendClanChatMessage(ptr int64 str)
@ cdecl SteamFriends_GetClanChatMessage(ptr int64 long ptr long ptr ptr)
@ cdecl SteamFriends_IsClanChatAdmin(ptr int64 int64)
@ cdecl SteamFriends_IsClanChatWindowOpenInSteam(ptr int64)
@ cdecl SteamFriends_OpenClanChatWindowInSteam(ptr int64)
@ cdecl SteamFriends_CloseClanChatWindowInSteam(ptr int64)
@ cdecl SteamFriends_SetListenForFriendsMessages(ptr long)
@ cdecl SteamFriends_ReplyToFriendMessage(ptr int64 str)
@ cdecl SteamFriends_GetFriendMessage(ptr int64 long ptr long ptr)
@ cdecl -ret64 SteamFriends_GetFollowerCount(ptr int64)
@ cdecl -ret64 SteamFriends_IsFollowing(ptr int64)
@ cdecl -ret64 SteamFriends_EnumerateFollowingList(ptr long)

# SteamApps API Calls
@ cdecl SteamApps_()
@ cdecl SteamApps_BIsSubscribed(ptr)
@ cdecl SteamApps_BIsLowViolence(ptr)
@ cdecl SteamApps_BIsCybercafe(ptr)
@ cdecl SteamApps_BIsVACBanned(ptr)
@ cdecl SteamApps_GetCurrentGameLanguage(ptr)
@ cdecl SteamApps_GetAvailableGameLanguages(ptr)
@ cdecl SteamApps_BIsSubscribedApp(ptr long)
@ cdecl SteamApps_BIsDlcInstalled(ptr long)
@ cdecl SteamApps_GetEarliestPurchaseUnixTime(ptr long)
@ cdecl SteamApps_BIsSubscribedFromFreeWeekend(ptr)
@ cdecl SteamApps_GetDLCCount(ptr)
@ cdecl SteamApps_BGetDLCDataByIndex(ptr long ptr ptr ptr long)
@ cdecl SteamApps_InstallDLC(ptr long)
@ cdecl SteamApps_UninstallDLC(ptr long)
@ cdecl SteamApps_RequestAppProofOfPurchaseKey(ptr long)
@ cdecl SteamApps_GetCurrentBetaName(ptr ptr long)
@ cdecl SteamApps_MarkContentCorrupt(ptr long)
@ cdecl SteamApps_GetInstalledDepots(ptr ptr long)
@ cdecl SteamApps_GetAppInstallDir(ptr long ptr long)

# SteamUserStats API Calls
@ cdecl SteamUserStats_()
@ cdecl SteamUserStats_RequestCurrentStats(ptr)
@ cdecl SteamUserStats_GetStatI(ptr str ptr)
@ cdecl SteamUserStats_GetStatF(ptr str ptr)
@ cdecl SteamUserStats_SetStatI(ptr str long)
@ cdecl SteamUserStats_SetStatF(ptr str float)
@ cdecl SteamUserStats_UpdateAvgRateStat(ptr str float double)
@ cdecl SteamUserStats_GetAchievement(ptr str ptr)
@ cdecl SteamUserStats_SetAchievement(ptr str)
@ cdecl SteamUserStats_ClearAchievement(ptr str)
@ cdecl SteamUserStats_GetAchievementAndUnlockTime(ptr str ptr ptr)
@ cdecl SteamUserStats_StoreStats(ptr)
@ cdecl SteamUserStats_GetAchievementIcon(ptr str)
@ cdecl SteamUserStats_GetAchievementDisplayAttribute(ptr str str)
@ cdecl SteamUserStats_IndicateAchievementProgress(ptr str long long)
@ cdecl SteamUserStats_GetNumAchievements(ptr)
@ cdecl SteamUserStats_GetAchievementName(ptr long)
@ cdecl SteamUserStats_RequestUserStats(ptr int64)
@ cdecl SteamUserStats_GetUserStatI(ptr int64 str ptr)
@ cdecl SteamUserStats_GetUserStatF(ptr int64 str ptr)
@ cdecl SteamUserStats_GetUserAchievement(ptr int64 str ptr)
@ cdecl SteamUserStats_GetUserAchievementAndUnlockTime(ptr int64 str ptr ptr)
@ cdecl SteamUserStats_ResetAllStats(ptr long)
# API calls returning a SteamAPICall_t are returning a uint64
# Unlike CSteamIDs, which get quirky depending on whether it's considered
# a struct or 64-bits of data, this should be safe to use with -ret64
@ cdecl -ret64 SteamUserStats_FindOrCreateLeaderboard(ptr str long long)
@ cdecl -ret64 SteamUserStats_FindLeaderboard(ptr str)
@ cdecl SteamUserStats_GetLeaderboardName(str int64)
@ cdecl SteamUserStats_GetLeaderboardEntryCount(ptr int64)
@ cdecl SteamUserStats_GetLeaderboardSortMethod(ptr int64)
@ cdecl SteamUserStats_GetLeaderboardDisplayType(ptr int64)
@ cdecl -ret64 SteamUserStats_DownloadLeaderboardEntries(ptr int64 long long long)
@ cdecl -ret64 SteamUserStats_DownloadLeaderboardEntriesForUsers(ptr int64 ptr long)
@ cdecl SteamUserStats_GetDownloadedLeaderboardEntry(ptr int64 long ptr ptr long)
@ cdecl -ret64 SteamUserStats_UploadLeaderboardScore(ptr int64 long long ptr long)
@ cdecl -ret64 SteamUserStats_AttachLeaderboardUGC(ptr int64 int64)
@ cdecl -ret64 SteamUserStats_GetNumberOfCurrentPlayers(ptr)
@ cdecl -ret64 SteamUserStats_RequestGlobalAchievementPercentages(ptr)
@ cdecl SteamUserStats_GetMostAchievedAchievementInfo(ptr ptr long ptr ptr)
@ cdecl SteamUserStats_GetNextMostAchievedAchievementInfo(ptr long ptr long ptr ptr)
@ cdecl SteamUserStats_GetAchievementAchievedPercent(ptr str ptr)
@ cdecl -ret64 SteamUserStats_RequestGlobalStats(ptr long)
@ cdecl SteamUserStats_GetGlobalStatI(ptr str ptr)
@ cdecl SteamUserStats_GetGlobalStatD(ptr str ptr)
@ cdecl SteamUserStats_GetGlobalStatHistoryI(ptr str ptr long)
@ cdecl SteamUserStats_GetGlobalStatHistoryD(ptr str ptr long)

# SteamUtils API Calls
@ cdecl steam_bridge_SteamUtils()
@ cdecl steam_bridge_SteamUtils_SetOverlayNotificationPosition(ptr long)

# Meta API calls
@ cdecl steam_bridge_version_string()
@ cdecl steam_bridge_info_string()
