// apps_api.h - Autogenerated header for ISteamApps
// Copyright (c) 2014 Bryan DeGrendel
//
// See COPYING and license/LICENSE.steambridge for license information

#pragma once

#include "types.h"

class ISteamApps;

class SteamApps
{
  public:
    virtual bool BIsSubscribed();
    virtual bool BIsLowViolence();
    virtual bool BIsCybercafe();
    virtual bool BIsVACBanned();
    virtual const char *GetCurrentGameLanguage();
    virtual const char *GetAvailableGameLanguages();
    virtual bool BIsSubscribedApp(AppId_t appID);
    virtual bool BIsDlcInstalled(AppId_t appID);
    virtual uint32 GetEarliestPurchaseUnixTime(AppId_t nAppID);
    virtual bool BIsSubscribedFromFreeWeekend();
    virtual int GetDLCCount();
    virtual bool BGetDLCDataByIndex(int iDLC, AppId_t *pAppID, bool *pbAvailable, char *pchName, int cchNameBufferSize);
    virtual void InstallDLC(AppId_t nAppID);
    virtual void UninstallDLC(AppId_t nAppID);
    virtual void RequestAppProofOfPurchaseKey(AppId_t nAppID);
    virtual bool GetCurrentBetaName(char *pchName, int cchNameBufferSize);
    virtual bool MarkContentCorrupt(bool bMissingFilesOnly);
    virtual uint32 GetInstalledDepots(DepotId_t *pvecDepots, uint32 cMaxDepots);
    virtual uint32 GetAppInstallDir(AppId_t appID, char *pchFolder, uint32 cchFolderBufferSize);

    SteamApps();

  private:
    ISteamApps *steamApps;

};
