#!/usr/bin/env python2.7
# config.py - Generates configuration files for the C/C++ and Python code.
# Copyright (c) 2014 Bryan DeGrendel
#
# See COPYING and license/LICENSE.steambridge for license information

import argparse, os

import utilities

options = utilities.Options()
parser = argparse.ArgumentParser(prog='configure',
    description='Configures SteamBridge source for compilation and installation')
parser.add_argument('--prefix',
        help='base prefix for installation; default is {}'.format(options.get('prefix')))
parser.add_argument('--proxy',
        help='location of the Win32 Proxy DLL; default is {}'.format(options.get('proxy_dll')))
args = parser.parse_args()

if args.prefix:
    options.set('prefix', args.prefix)

if args.proxy:
    options.set('proxy_dll', args.proxy)

print 'Installation prefix: {}'.format(options.get('prefix'))
print 'User directory: {}'.format(options.get('local'))
print 'Win32 Proxy DLL location: {}'.format(options.get('proxy_dll'))
print 'Steam root: {}'.format(options.get('steam_root'))
print ''

options.save()
print 'Saved configuration options'

# TODO: Check for compiler/libraries/etc here?

config = options.configure()

config_header = open('libraries/common/include/config.h', 'w')
config_header.write("""#ifndef ___STEAM_BRIDGE_CONFIG_H___
#define ___STEAM_BRIDGE_CONFIG_H___

// NOTICE: This file is automatically generated by make config.
//         See installation/settings.py for instructions on how to
//         modify it.

#define _STEAM_BRIDGE_APPNAME "{steambridge[app_name]}"
#define _STEAM_BRIDGE_WEBPAGE "{steambridge[webpage]}"

#define _STEAM_BRIDGE_VERSION_MAJOR {steambridge[version][major]}
#define _STEAM_BRIDGE_VERSION_MINOR {steambridge[version][minor]}
#define _STEAM_BRIDGE_VERSION_PATCH {steambridge[version][patch]}

#define _STEAM_BRIDGE_VERSION_SHORT "{steambridge[version][short]}"
#define _STEAM_BRIDGE_VERSION_LONG "{steambridge[version][long]}"

#define _STEAM_BRIDGE_LOCAL "{steambridge[local][root]}"
#define _STEAM_BRIDGE_CONFIG "{steambridge[local][config]}"
#define _STEAM_BRIDGE_APPDB_ROOT "{steambridge[local][appdb]}"
#define _STEAM_BRIDGE_APPDB_CONFIG "{steambridge[local][appdb_config_filename]}"

#define _STEAM_BRIDGE_API_LIB "{steambridge[prefix][steam_api_lib]}"

#endif //___STEAM_BRIDGE_CONFIG_H___
""".format(**config))
config_header.close()
print 'Generated common C header'

python_config = open('tools/pysteambridge/config.py', 'w')
python_config.write("""# NOTICE: This file is automatically generated by make config.
#         See common/settings.py for instructions on how to modify it.

import os

HOME_DIR=os.path.expanduser('~')

def _p(path):
  if len(path) >= 1 and path[0] == '~':
    return HOME_DIR + path[1:]
  else:
    return path

# Root directory of the local steam installation
STEAM_ROOT=_p('{steam[root]}')

# Location of appmanifest_*.acf files
STEAM_APPMANIFESTS=_p('{steam[app_manifests]}')

# Common root of installed Steam games
STEAM_APPS=_p('{steam[apps]}')

# Root directory of the user's SteamBridge deployment
STEAM_BRIDGE_LOCAL=_p('{steambridge[local][root]}')

# Configuration filename, used by the C++ library
CONFIG_FILENAME=_p('{steambridge[local][config]}')

# Root directory of the SteamBridge installation
STEAM_BRIDGE_PREFIX=_p('{steambridge[prefix][root]}')

# Location of the Win32 native steam_api proxy DLL
# This is the location when it's deployed
PROXY_DLL=_p('{steambridge[prefix][proxy_dll]}')

# Location of the Winelib bridge library
BRIDGE_LIB=_p('{steambridge[prefix][bridge_lib]}')

# Location of Winelib DLL, used as WINEDLLPATH
WINEDLLPATH=_p('{steambridge[prefix][winedllpath]}')

# Location of the native Linux steam_api library
STEAM_API_LIB=_p('{steambridge[prefix][steam_api_lib]}')

# Root directory of the internal AppDB
APPDB_ROOT=_p('{steambridge[local][appdb]}')

# AppDB configuration filename
APPDB_CONFIG='{steambridge[local][appdb_config_filename]}'

# Directory storing the main steambridge client script
BIN_DIR=_p('{steambridge[prefix][bin]}')

# Directory storing the Python Runtime library
PYSTEAMBRIDGE_DIR=_p('{steambridge[prefix][pysteambridge]}')

# The official, formal name of the library
APP_NAME='{steambridge[app_name]}'

# The formal copyright statement
COPYRIGHT='{steambridge[copyright]}'

# Version string information
VERSION_MAJOR={steambridge[version][major]}
VERSION_MINOR={steambridge[version][minor]}
VERSION_PATCH={steambridge[version][patch]}

VERSION_SHORT='{steambridge[version][short]}'
VERSION_LONG='{steambridge[version][long]}'
""".format(**config))
python_config.close()
print 'Generated Python runtime configuration'

print ''
print 'Configuration complete'

