#!/usr/bin/env python2.7
# config.py - Generates configuration files for the C/C++ and Python code.
# Copyright (c) 2014 Bryan DeGrendel
#
# See COPYING and license/LICENSE.steambridge for license information

import utilities

options = utilities.defaults()
settings = utilities.settings(options)
directories = utilities.directories(options)

config_header = open('common/include/config.h', 'w')

config_header.write("""#ifndef ___STEAM_BRIDGE_CONFIG_H___
#define ___STEAM_BRIDGE_CONFIG_H___

// NOTICE: This file is automatically generated by make config.
//         See installation/settings.py for instructions on how to
//         modify it.

#define _STEAM_BRIDGE_APPNAME "{settings[app_name]}"
#define _STEAM_BRIDGE_WEBPAGE "{settings[webpage]}"

#define _STEAM_BRIDGE_VERSION_MAJOR {settings[version][major]}
#define _STEAM_BRIDGE_VERSION_MINOR {settings[version][minor]}
#define _STEAM_BRIDGE_VERSION_PATCH {settings[version][patch]}

#define _STEAM_BRIDGE_VERSION_SHORT "{settings[version][short]}"
#define _STEAM_BRIDGE_VERSION_LONG "{settings[version][long]}"

#define _STEAM_BRIDGE_LOCAL "{directories[steambridge][local][root]}"
#define _STEAM_BRIDGE_CONFIG "{directories[steambridge][local][config]}"
#define _STEAM_BRIDGE_APPDB_ROOT "{directories[steambridge][local][appdb]}"
#define _STEAM_BRIDGE_APPDB_CONFIG "{directories[steambridge][local][appdb_config_filename]}"

#define _STEAM_BRIDGE_API_LIB "{directories[steambridge][prefix][steam_api_lib]}"

#endif //___STEAM_BRIDGE_CONFIG_H___
""".format(settings=settings, directories=directories))
config_header.close()

python_config = open('interface/pysteambridge/config.py', 'w')
python_config.write("""# NOTICE: This file is automatically generated by make config.
#         See common/settings.py for instructions on how to modify it.

# Root directory of the local steam installation
STEAM_ROOT="{directories[steam][root]}"

# Location of appmanifest_*.acf files
STEAM_APPMANIFESTS="{directories[steam][app_manifests]}"

# Common root of installed Steam games
STEAM_APPS="{directories[steam][apps]}"

# Root directory of the user's SteamBridge deployment
STEAM_BRIDGE_LOCAL="{directories[steambridge][local][root]}"

# Configuration filename, used by the C++ library
CONFIG_FILENAME="{directories[steambridge][local][config]}"

# Root directory of the SteamBridge installation
STEAM_BRIDGE_PREFIX="{directories[steambridge][prefix][root]}"

# Location of the Win32 native steam_api proxy DLL
# This is the location when it's deployed
PROXY_DLL="{directories[steambridge][prefix][proxy_dll]}"

# Location of the Winelib bridge library
BRIDGE_LIB="{directories[steambridge][prefix][bridge_lib]}"

# Location of Winelib DLL, used as WINEDLLPATH
WINEDLLPATH="{directories[steambridge][prefix][winedllpath]}"

# Location of the native Linux steam_api library
STEAM_API_LIB="{directories[steambridge][prefix][steam_api_lib]}"

# Root directory of the internal AppDB
APPDB_ROOT="{directories[steambridge][local][appdb]}"

# AppDB configuration filename
APPDB_CONFIG="{directories[steambridge][local][appdb_config_filename]}"

# Directory storing the main steambridge client script
BIN_DIR="{directories[steambridge][prefix][bin]}"

# Directory storing the Python Runtime library
PYSTEAMBRIDGE_DIR="{directories[steambridge][prefix][pysteambridge]}"

# The official, formal name of the library
APP_NAME="{settings[app_name]}"

# The formal copyright statement
COPYRIGHT="{settings[copyright]}"

# Version string information
VERSION_MAJOR={settings[version][major]}
VERSION_MINOR={settings[version][minor]}
VERSION_PATCH={settings[version][patch]}

VERSION_SHORT="{settings[version][short]}"
VERSION_LONG="{settings[version][long]}"
""".format(settings=settings, directories=directories))
python_config.close()

